/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BokningarIndexRouteImport } from './routes/bokningar.index'
import { Route as BokningarIdRouteImport } from './routes/bokningar.$id'
import { Route as BokningarNyRouteImport } from './routes/bokningar.ny'
import { Route as EventIndexRouteImport } from './routes/event.index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as EventNyRouteImport } from './routes/event.ny'
import { Route as EventIdDeltagareRouteImport } from './routes/event.$id_.deltagare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningarIndexRoute = BokningarIndexRouteImport.update({
  id: '/bokningar/',
  path: '/bokningar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningarIdRoute = BokningarIdRouteImport.update({
  id: '/bokningar/$id',
  path: '/bokningar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BokningarNyRoute = BokningarNyRouteImport.update({
  id: '/bokningar/ny',
  path: '/bokningar/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNyRoute = EventNyRouteImport.update({
  id: '/event/ny',
  path: '/event/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdDeltagareRoute = EventIdDeltagareRouteImport.update({
  id: '/event/$id_/deltagare',
  path: '/event/$id/deltagare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bokningar/$id': typeof BokningarIdRoute
  '/bokningar/ny': typeof BokningarNyRoute
  '/event/$id': typeof EventIdRoute
  '/event/ny': typeof EventNyRoute
  '/bokningar/': typeof BokningarIndexRoute
  '/event/': typeof EventIndexRoute
  '/event/$id/deltagare': typeof EventIdDeltagareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bokningar/$id': typeof BokningarIdRoute
  '/bokningar/ny': typeof BokningarNyRoute
  '/event/$id': typeof EventIdRoute
  '/event/ny': typeof EventNyRoute
  '/bokningar': typeof BokningarIndexRoute
  '/event': typeof EventIndexRoute
  '/event/$id/deltagare': typeof EventIdDeltagareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bokningar/$id': typeof BokningarIdRoute
  '/bokningar/ny': typeof BokningarNyRoute
  '/event/$id': typeof EventIdRoute
  '/event/ny': typeof EventNyRoute
  '/bokningar/': typeof BokningarIndexRoute
  '/event/': typeof EventIndexRoute
  '/event/$id_/deltagare': typeof EventIdDeltagareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bokningar/$id'
    | '/bokningar/ny'
    | '/event/$id'
    | '/event/ny'
    | '/bokningar/'
    | '/event/'
    | '/event/$id/deltagare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bokningar/$id'
    | '/bokningar/ny'
    | '/event/$id'
    | '/event/ny'
    | '/bokningar'
    | '/event'
    | '/event/$id/deltagare'
  id:
    | '__root__'
    | '/'
    | '/bokningar/$id'
    | '/bokningar/ny'
    | '/event/$id'
    | '/event/ny'
    | '/bokningar/'
    | '/event/'
    | '/event/$id_/deltagare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokningarIdRoute: typeof BokningarIdRoute
  BokningarNyRoute: typeof BokningarNyRoute
  EventIdRoute: typeof EventIdRoute
  EventNyRoute: typeof EventNyRoute
  BokningarIndexRoute: typeof BokningarIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  EventIdDeltagareRoute: typeof EventIdDeltagareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningar/': {
      id: '/bokningar/'
      path: '/bokningar'
      fullPath: '/bokningar/'
      preLoaderRoute: typeof BokningarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningar/$id': {
      id: '/bokningar/$id'
      path: '/bokningar/$id'
      fullPath: '/bokningar/$id'
      preLoaderRoute: typeof BokningarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bokningar/ny': {
      id: '/bokningar/ny'
      path: '/bokningar/ny'
      fullPath: '/bokningar/ny'
      preLoaderRoute: typeof BokningarNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/ny': {
      id: '/event/ny'
      path: '/event/ny'
      fullPath: '/event/ny'
      preLoaderRoute: typeof EventNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id_/deltagare': {
      id: '/event/$id_/deltagare'
      path: '/event/$id/deltagare'
      fullPath: '/event/$id/deltagare'
      preLoaderRoute: typeof EventIdDeltagareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokningarIdRoute: BokningarIdRoute,
  BokningarNyRoute: BokningarNyRoute,
  EventIdRoute: EventIdRoute,
  EventNyRoute: EventNyRoute,
  BokningarIndexRoute: BokningarIndexRoute,
  EventIndexRoute: EventIndexRoute,
  EventIdDeltagareRoute: EventIdDeltagareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}